### ISSUE TITLE
Can not create

### ISSUE THREAD

**Issue by XavierDare** [Arathok/FuelStorage#1]
I am attempting to create this in our server but it says you must carry it to work with it. However you can not carry a small crate.

![image](https://user-images.githubusercontent.com/64657541/160655675-ef4e32bb-f5bc-4ed6-ac6c-049161932af4.png)
![image](https://user-images.githubusercontent.com/64657541/160655734-1dc68d6c-4f64-4219-a4f1-75e232df0b45.png)

**Comment by Arathok** [comment]
Hmm wasn't a small crate empty being able to picked up? Then I will break the small crate down i to it's components and add them to the needed components on the fuel storage.

Will upload a fix by tomorrow!

**Comment by XavierDare** [comment]
Yea even an empty small crate can not be picked up (a small chest can tho). Thank you!

**Comment by Arathok** [comment]
Thanks for spotting it! Fixed!
https://github.com/Arathok/FuelStorage/releases/tag/2.2
