### ISSUE TITLE
Does not work on linux servers without changes

### ISSUE THREAD

**Issue by Tokeiito** [Arathok/FuelStorage#3]
Linux servers are case sensitive. In mod properties following definitions are:

classpath=fuelstorage.jar
serverPacks=fuelstorage-pack.jar

While file names for those jars are named as follows:

fuelStorage.jar
fuelStorage-pack.jar

on linux, at least on Ubuntu 20.04 it causes wu server mod loader not to find necessary files and  mod class. Renaming the files in properties helps.

**Comment by Arathok** [comment]
Also cleaned up, Thanks again!
